version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ressist-backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./sessions:/sessions
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ressist-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

networks:
  default:
    name: ressist-network